name        : makedepend
version     : 1.0.5
release     : 3
source     :
    - http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.5.tar.gz : 503903d41fb5badb73cb70d7b3740c8b30fe1cc68c504d3b6a85e6644c4e5004
license     :
    - MIT
summary     : X11 utility to determine build-time dependencies
component   : xorg.base
builddeps   :
    - pkgconfig(xproto)
description : |
    The makedepend package contains a C-preprocessor like utility to determine build-time dependencies.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
