name       : makedepend
version    : 1.0.7
release    : 10
source     :
    - http://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.7.tar.gz : 17c1adf0284aaee473abfff0e8d3e754770615e1275f2a0043b9d97a00ed5cc9
license    : MIT
component  : xorg.base
summary    : X11 utility to determine build-time dependencies
description: |
    The makedepend package contains a C-preprocessor like utility to determine build-time dependencies.
builddeps  :
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
